spring:
  json:
    use:
      type:
        headers: true
  application:
    name: spring-boot-kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    #?????????????????????????????????
    producer:
      #??????????
      batch-size: 16
      #????0?????????????????????????????????????????????????????????????????????????????????????????partition???????????????????????????????????
      retries: 0
      #producer?????????????????????????broker??????producer????????????block.on.buffer.full???????????producer???????????????????????????producer??????????????????????????????????????????????????
      buffer-memory: 33554432
      #key?????
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.trusted.packages: com.sxia.model.Book
#        spring.add.type.headers: false
    #??????
    consumer:
      #Kafka????????????????????????,????? ?????? ?latest, earliest, none?
      auto-offset-reset: latest
      #????????
      enable-auto-commit: true
      #?????????
      auto-commit-interval: 100
      #key?????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value?????
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #?/usr/local/etc/kafka/consumer.properties????
      group-id: kafka-test